### ISSUE TITLE
Generated PDFs: replace login-name with display-name, if set

### ISSUE THREAD

**Issue by t-markmann** [t-markmann/nc-userimporter#15]
"Hello _login-name_," should be "Hello _display-name_," if the display-name is set.

**Comment by Shen** [comment]
This should already be fixed here:
https://github.com/t-markmann/nc-userimporter/commit/320d76e0abd4710e5ab7d13688de0d4c503f6d58#diff-e5106c8bf1b7945a8792a7ad695a63e7R532

**Comment by nephx** [comment]
Still not working in current version. Login-name is still shown in pdfs for % ncusername

**Comment by t-markmann** [comment]
Just tested it. Display Name is taken in my test.

![grafik](https://user-images.githubusercontent.com/5323995/98292595-3a215b80-1fad-11eb-83c2-b162c23dfbfc.png)

    <language>de</language>
    <EduDocs>no</EduDocs>
    <schoolgroup>Lehrkraefte</schoolgroup>
